apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: dev
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-c
    image: acadalearning/java-web-app
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: websvc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
